@startuml

skinparam handwritten true
skinparam backgroundColor white

title ユースケース：カスタムエントリー

actor ユーザー
actor 閲覧ユーザー

package カスタムエントリー {
	left to right direction
	ユーザー -up-> (エントリー管理)
	(エントリー管理) -up-> (エントリー一覧を表示する)
	(エントリー管理) -up-> (エントリーを作成する)
	(エントリー管理) -up-> (エントリーを編集する)
	(エントリー管理) -up-> (エントリーを削除する)
	(エントリー管理) -up-> (エントリーを一括削除する)
	(エントリー一覧を表示する) -up-> (エントリーを公開状態・非公開状態に設定する)
	(エントリー一覧を表示する) -up-> (エントリーをコピーする)
	(エントリー一覧を表示する) -up-> (エントリーを削除する)
	閲覧ユーザー -down-> (フロントのエントリー一覧を表示する)
	閲覧ユーザー -down-> (フロントのエントリー詳細を表示する)
}

@enduml
	
	
	
	
