@startuml

skinparam handwritten true
skinparam backgroundColor white

title ユースケース：カスタムテーブル

actor ユーザー

package カスタムテーブル {
	left to right direction
	ユーザー -up-> (カスタムテーブル一覧を表示する)
	ユーザー -up-> (カスタムテーブルを新規登録する)
	ユーザー -up-> (カスタムテーブルを編集する)
	ユーザー -up-> (カスタムテーブルを削除する)
	ユーザー -up-> (カスタムフィールドと関連付ける)
	ユーザー -up-> (カスタムフィールドとの関連付けを削除する)
	ユーザー -up-> (関連フィールドの並び順を変更する)
	ユーザー -up-> (プレビューを確認する)
	note bottom of プレビューを確認する
		コンテンツ管理と連携する場合
	end note
}

@enduml
