@startuml
skinparam handwritten true
skinparam backgroundColor white
hide circle
skinparam classAttributeIconSize 0

title アクセスルールグループAPI

class Admin\PermissionGroupsController {
  + アクセスルールグループ単一データ取得：index()
  + アクセスルールグループ一覧取得：index()
  + アクセスルールグループ新規追加：add()
  + アクセスルールグループ編集：edit()
  + アクセスルールグループ削除：delete()
  + ユーザーグループごとに\nアクセスルール再構築：rebuild_by_user_group()
}

class PermissionGroupsService {
  + PermissionGroupsTable
}

Admin\PermissionGroupsController -down[#Black]-> PermissionGroupsService

note "以下アクセスルールグループ管理と同じ" as pageNote
PermissionGroupsService .. pageNote

@enduml
