@startuml
skinparam handwritten true
skinparam backgroundColor white
hide method

title ドメインモデル図：カスタムフィールド

package カスタムフィールド {
	
	class カスタムフィールド {
		カスタムコンテンツID
		カスタムフィールドNO
		フィールド名
		タイトル
		フィールドタイプ
		項目見出し
		注意書き
		前見出し
		後見出し
		選択リスト
		表示サイズ
		行数
		最大値
		オプション
		クラス
		区切り文字
		初期値
		説明文
		グループ名
		グループ入力チェック
		入力チェック
		拡張入力チェック
		自動変換
		必須マーク
		利用状態
		メール送信しない
		並び順
		オートコンプリート
	}

}

カスタムフィールド "0..*" -right- "1" カスタムコンテンツ

@enduml
