@startuml
skinparam handwritten true
skinparam backgroundColor white
hide method

title ドメインモデル図：カスタムフィールド

package カスタムフィールド {
	
	class カスタムフィールド {
		カスタムテーブルID
		カスタムフィールドNO
		親ID
		ツリー構造左位置
		ツリー構造右位置
		項目見出し
		フィールド名
		フィールドタイプ
		ステータス
		入力必須とする
		前見出し
		後見出し
		説明文
		注意書き
		登録日
		変更日
		グループ入力チェック
		オプション
		クラス
		初期値
		入力チェック
		正規表現入力
		エラー用文言
		文字数カウンターを表示する
		自動変換
		プレースホルダー
		サイズ
		テキスト行数
		最大値
		選択肢
		メタ情報
	}

}

カスタムフィールド "1" -up- "0..*" カスタムフィールドセット
カスタムフィールドセット "0..*" -up- "1" カスタムテーブル

@enduml
