@startuml
skinparam handwritten true
skinparam backgroundColor white
hide method

title ドメインモデル図：カスタムエントリー

package カスタムエントリー {
	
	class カスタムエントリー {
		カスタムテーブルID
		NO
		スラッグ
		タイトル
		作成者ID
		登録日
		公開状態（カテゴリの場合に検討要）
		公開開始日（カテゴリの場合に検討要）
		公開終了日（カテゴリの場合に検討要）
		サイト内検索より除外（カテゴリの場合に検討要）
		アイキャッチ（カテゴリの場合に検討要）
	}

}
 
カスタムエントリー "0..*" -up- "1" カスタムテーブル
カスタムエントリー "0..*" -up- "1" 親カスタムエントリー


@enduml
