@startuml
object settings {
    fields
- eyecatchなど
  ・name : string
  ・namefield : string
  ・type : string
  ・nameadd : bool
  ・nameformat : string
  ・subdirDateFormat : string
  ・getUniqueFileName : bool
  ・ext : string
  ・upload : bool
  ・imagecopy : array
   ・thumb
   ・medium
  ・imageresize : array
   ・thumb
}
object uploadedFIle {
    - eyecatchなど
 ・tmp_name
 ・error
 ・name
 ・type
 ・size
}
object savePath
object existsCheckDirs
object tmpId
object imgExts
object uploaded

@enduml