@startuml
skinparam handwritten true
skinparam backgroundColor white
hide circle
skinparam classAttributeIconSize 0

title 検索インデックスAPI

class Api\SearchIndexesController { 
	+ 一覧表示：index()
	+ 削除：delete()
	+ 優先度変更：change_priority()
	+ 再構築：reconstruct()
	+ 検索：search()
}

class SearchIndexesService {
}


Api\SearchIndexesController -down-> SearchIndexesService

note "以下サイト管理と同じ" as note
SearchIndexesService .. note

@enduml
