@startuml
skinparam handwritten true
skinparam backgroundColor white
hide circle
skinparam classAttributeIconSize 0

title ブログカテゴリAPI

class Api\BlogCategoriesController {
  + ブログカテゴリー一覧取得：index()
  + 単一ブログカテゴリー取得：view()
  + ブログカテゴリーリスト取得：list()
  + ブログカテゴリー新規追加：add()
  + ブログカテゴリー編集：edit()
  + ブログカテゴリー削除：delete()
  + ブログカテゴリー一括処理：batch()
}

Api\BlogCategoriesController -down[#Black]-> BlogCategoriesService
Api\BlogCategoriesController -up[#Black]-|> BcApiController

note "以下ブログカテゴリ管理と同じ" as note
BlogCategoriesService .. note

@enduml
