@startuml
skinparam handwritten true
skinparam backgroundColor white
hide circle
skinparam classAttributeIconSize 0

title ブログコンテンツAPI

class Api\BlogContentsController {
  + 一覧取得：index()
  + 単一データ取得：view()
  + リスト取得：list()
  + 新規追加：add()
  + 編集：edit()
  + 削除：delete()
  + コピー：copy()
}

Api\BlogContentsController -down[#Black]-> BlogContentsService
Api\BlogContentsController -up[#Black]-|> BcApiController

note "以下ブログコンテンツ管理と同じ" as note
BlogContentsService .. note

@enduml
