@startuml
skinparam handwritten true
skinparam backgroundColor white
hide circle
skinparam classAttributeIconSize 0

title カスタムエントリー管理

class Api\CustomEntriesController {
  + 一覧を表示：index()
  + 単一データ表示：view()
  + 新規追加：add()
  + 編集：edit()
  + 削除：delete()
	+ 複製：copy()
	+ 公開状態に設定：publish()
	+ 非公開状態に設定：unpublish()
	+ 一括処理：batch()
}

class CustomEntriesService {
  + CustomEntriesTable
}

Api\CustomEntriesController -down[#Black]-> CustomEntriesService

note "以下カスタムポスト管理と同じ" as note
CustomEntriesService .. note

@enduml
