@startuml
skinparam handwritten true
skinparam backgroundColor white
hide circle
skinparam classAttributeIconSize 0

title カスタムポスト管理

class Api\CustomPostsController {
  + 一覧を表示：index()
  + 単一データ表示：view()
  + 新規追加：add()
  + 編集：edit()
  + 削除：delete()
	+ 複製：copy()
	+ 公開状態に設定：publish()
	+ 非公開状態に設定：unpublish()
	+ 一括処理：batch()
}

class CustomPostsService {
  + CustomPostsTable
}

Api\CustomPostsController -down[#Black]-> CustomPostsService

note "以下カスタムポスト管理と同じ" as note
CustomPostsService .. note

@enduml
