@startuml

skinparam handwritten true
skinparam backgroundColor white

title ユースケース：ブログ記事

actor ユーザー
actor 閲覧ユーザー

package ブログ記事 {
	left to right direction
	ユーザー -up-> (ブログ記事管理)
	(ブログ記事管理) -up-> (ブログ記事一覧を表示する)
	(ブログ記事管理) -up-> (ブログ記事を作成する)
	(ブログ記事管理) -up-> (ブログ記事を編集する)
	(ブログ記事管理) -up-> (ブログ記事を削除する)
	(ブログ記事管理) -up-> (ブログ記事を一括削除する)
	(ブログ記事一覧を表示する) -up-> (記事を公開状態・非公開状態に設定する)
	(ブログ記事一覧を表示する) -up-> (記事をコピーする)
	(ブログ記事一覧を表示する) -up-> (記事を削除する)
	(ブログ記事を作成する) -up-> (新しいカテゴリを追加する)
	(ブログ記事を作成する) -up-> (新しいタグを追加する)
	閲覧ユーザー -down-> (フロントの最新記事一覧を表示する)
	閲覧ユーザー -down-> (フロントのカテゴリ別記事一覧を表示する)
	閲覧ユーザー -down-> (フロントのタグ別記事一覧を表示する)
	閲覧ユーザー -down-> (フロントの年別記事一覧を表示する)
	閲覧ユーザー -down-> (フロントの月別記事一覧を表示する)
	閲覧ユーザー -down-> (フロントの日別記事一覧を表示する)
	閲覧ユーザー -down-> (フロントの著者別記事一覧を表示する)
	閲覧ユーザー -down-> (フロントの記事詳細を表示する)
	(フロントの記事詳細を表示する) -down-> (記事にコメントする)
}

@enduml
	
	
	
	
