@startuml
skinparam handwritten true
skinparam backgroundColor white

title ユースケース：コンテンツ管理

left to right direction

actor 作成者

package コンテンツ管理 {
	作成者 --> (ツリー形式で一覧を表示する)
	作成者 --> (表形式で一覧を表示する)
	作成者 --> (一覧表示形式切替)
}

package ツリー形式 {
	(ツリー形式で一覧を表示する) --> (ツリー形式でコンテンツを操作する) 
	(ツリー形式で一覧を表示する) --> (ツリーを全て展開)
	(ツリー形式で一覧を表示する) --> (ツリーを全て閉じる)
}

package 表形式 {
	(表形式で一覧を表示する) --> (表形式でコンテンツを操作する) 
}

package コンテンツ操作 {
	(ツリー形式でコンテンツを操作する) -[#green]-> (コンテンツを作成する)
	(ツリー形式でコンテンツを操作する) -[#green]-> (コンテンツのエイリアスを作成する)
	(ツリー形式でコンテンツを操作する) -[#green]-> (コンテンツを並び替える)
	(ツリー形式でコンテンツを操作する) -[#green]-> (コンテンツの名称を変更する)
	(ツリー形式でコンテンツを操作する) -[#green]-> (コンテンツを編集する)
	(ツリー形式でコンテンツを操作する) -[#green]-> (コンテンツを公開する)
	(ツリー形式でコンテンツを操作する) -[#green]-> (コンテンツを非公開にする)
	(ツリー形式でコンテンツを操作する) -[#green]-> (コンテンツを確認する)
	(ツリー形式でコンテンツを操作する) -[#green]-> (コンテンツをコピーする)
	(ツリー形式でコンテンツを操作する) -[#green]-> (コンテンツを削除する)
	(表形式でコンテンツを操作する) -[#red]-> (コンテンツを編集する)
	(表形式でコンテンツを操作する) -[#red]-> (コンテンツを公開する)
	(表形式でコンテンツを操作する) -[#red]-> (コンテンツを非公開にする)
	(表形式でコンテンツを操作する) -[#red]-> (コンテンツを確認する)
	(表形式でコンテンツを操作する) -[#red]-> (コンテンツをコピーする)
	(表形式でコンテンツを操作する) -[#red]-> (コンテンツを削除する)
	(表形式でコンテンツを操作する) -[#red]-> (コンテンツを検索する)
	(表形式でコンテンツを操作する) -[#red]-> (コンテンツの一括処理を行う)
}

package コンテンツ詳細 {
	(コンテンツを編集する) --> (関連コンテンツとしてコピーを作成する)
	(コンテンツを編集する) --> (関連コンテンツとしてエイリアスを作成する)
}

	
note left of コンテンツ管理
「コンテンツ」はフォルダ、固定ページ、リンク、エイリアスなど
複数の種類のコンテンツを対象とする。
endnote

note left of (コンテンツを削除する)
削除した場合はゴミ箱に入る
endnote

@enduml
