@startuml
skinparam handwritten true
skinparam backgroundColor white

title ユースケース：ユーザー管理

actor 管理者

package ユーザー管理 {
	left to right direction
	管理者 --> (プラグイン一覧を表示する)
	管理者 --> (プラグインを新規登録する)
	note right of (プラグインを新規登録する)
	・Zipファイルをアップロードし解答して配置
	・.htaccessファイルが含まれるプラグインはアップロードできない
	・データベースへの登録（インストール）は行わない
	endnote
	管理者 --> (プラグインをインストールする)
	note right of (プラグインをインストールする)
	・インストールスクリプトを実行しデータベースへ登録する
	endnote
	管理者 --> (プラグインを無効化する)
	note right of (プラグインを無効化する)
	・ステータスを無効にするのみ
	endnote
	管理者 --> (プラグインを有効化する)
	note right of (プラグインを有効化する)
	・ステータスを有効にするのみ
	endnote
	管理者 --> (プラグインのデータベースの\nデータを初期化する)
	note right of (プラグインのデータベースの\nデータを初期化する)
	・プラグインが無効、かつ、初期済の場合のみ実行可能
	endnote
	管理者 --> (プラグインをアンインストールする)
	note right of (プラグインをアンインストールする)
	・プラグインが無効の場合のみ実行可能
	・データベースから削除し、プラグインのソースコードも削除する。
	endnote
	管理者 --> (プラグインを一括無効化する)
	管理者 --> (プラグインのイベントコールバック処理の\n優先度の並べ替えを行う)
	管理者 --> (プラグインのアップデートを行う)
	note right of (プラグインのアップデートを行う)
	・プラグインのソースコードのバージョン番号より、
	データベースに登録されているバージョン番号の方が
	古い場合に実行できる。
	・実行時にはアップデートスクリプトを実行する
	endnote
	管理者 --> (baserマーケットのプラグイン一覧を表示する)
}

@enduml
