@startuml
skinparam handwritten true
skinparam backgroundColor white

title ユースケース：ユーザー管理

actor 管理者

package ユーザー管理 {
	left to right direction
	管理者 --> (プラグイン一覧を表示する)
	管理者 --> (プラグインを新規登録する)
	管理者 --> (プラグインをインストールする)
	管理者 --> (プラグインを無効化する)
	管理者 --> (プラグインを有効化する)
	管理者 --> (プラグインのデータベースのデータを初期化する)
	管理者 --> (プラグインを削除する)
	管理者 --> (プラグインを一括無効化する)
	管理者 --> (プラグインのイベントコールバック処理の優先度の並べ替えを行う)
}

@enduml
