@startuml

skinparam handwritten true
skinparam backgroundColor white

title ユースケース：検索インデックス

actor 閲覧ユーザー
actor ユーザー
actor 管理者

package 検索インデックス {
	left to right direction
	ユーザー -up-> (コンテンツ作成時に連携して作成する)
	ユーザー -up-> (コンテンツ更新時に連携して更新する)
	ユーザー -up-> (コンテンツ削除時に連携して削除する)
	管理者 -down-> (検索・一覧表示する)
	管理者 -down-> (削除する)
	管理者 -down-> (一括削除する)
	管理者 -down-> (優先度を変更する)
	閲覧ユーザー -down-> (フロントページで検索・一覧表示する)
}


@enduml
