@startuml
skinparam handwritten true
skinparam backgroundColor white

title ユースケース：サイト管理

actor 管理者

package サイト管理 {
	left to right direction
	管理者 --> (基本項目)
	(基本項目) --> (管理者メールアドレスを設定する)
	(基本項目) --> (WebサイトのURLを設定する)
	(基本項目) --> (公開状態を切り替える)
	(基本項目) --> (制作・開発モードを切り替える)
	管理者 --> (管理画面設定)
	(管理画面設定) --> (管理画面のSSLを設定する)
	(管理画面設定) --> (管理画面のテーマを切り替える)
	(管理画面設定) --> (管理画面の一覧の初期表示件数を切り替える)
	(管理画面設定) --> (ログインページのクレジット表示を設定する)
	(管理画面設定) --> (管理画面のサイドバーのバナー表示を設定する)
	管理者 --> (サイト設定)
	(サイト設定) --> (デバイス言語設定を切り替える)
	管理者 --> (エディタ設定)
	(エディタ設定) --> (編集画面で利用するエディタのタイプを切り替える)
	(エディタ設定) --> (編集画面で利用するエディタの改行モードを切り替える)
	(エディタ設定) --> (編集画面で利用するエディタのスタイルセットを設定する)
	管理者 --> (メール設定)
	(メール設定) --> (メールの送信文字コードを設定する)
	(メール設定) --> (メール送信時のSMTP情報を設定する)
	(メール設定) --> (メールの送信テストを行う)
	(メール設定) --> (メール送信時のadditional_parametersを設定する)
	
}

@enduml
