@startuml
skinparam handwritten true

title ユースケース：ファイルアップロード

actor 作成者

package ファイルアップロード {
	left to right direction
	作成者 --> (ファイルをアップロードする)
	作成者 --> (ファイルを削除する)
	作成者 --> (アップロードの際に別サイズの画像を作成する)
		note right of アップロードの際に別サイズの画像を作成する
		画像ファイルの場合
		endnote
	作成者 --> (アップロード済のファイルをポップアップで表示する)
		note right of アップロード済のファイルをポップアップで表示する
		画像ファイルの場合
		endnote
	作成者 --> (アップロード済のファイルをダウンロードする)
		note right of アップロード済のファイルをダウンロードする
		画像ファイル以外の場合
		endnote
	作成者 --> (アップロード済のファイルをプレビューで表示する)
	作成者 --> (未アップロードのファイルをプレビューで表示する)
}


@enduml
