@startuml
skinparam handwritten true
skinparam backgroundColor white

title ユースケース：ユーザー管理

actor 管理者

package ユーザー管理 {
	left to right direction
	管理者 --> (ユーザー一覧を表示する)
	管理者 --> (ユーザー一覧で絞り込む)
	管理者 --> (代理ログインを行う)
	note right of 代理ログインを行う
	システム管理ユーザーがシステム管理ユーザー以外の
	ユーザーに対してログインできる
	endnote
	管理者 --> (代理ログインを解除する)
	管理者 --> (ユーザーを作成する)
	管理者 --> (ユーザーを編集する)
	管理者 --> (ユーザーを削除する)
	管理者 --> (ログイン)
	管理者 --> (ログアウト)
	管理者 --> (ログイン状態を保存する)
	管理者 --> (パスワードを再発行する)
}

@enduml
