@startuml
skinparam handwritten true
skinparam backgroundColor white

title ユースケース：ユーティリティ

actor 管理者

package ユーティリティ {
	left to right direction
	管理者 --> (ユーティリティトップを表示する)
	管理者 --> (サーバーキャッシュを削除する)
	管理者 --> (コンテンツ管理のツリー構造をチェックする)
	管理者 --> (コンテンツ管理のツリー構造をリセットする)
	管理者 --> (スペシャルサンクスクレジットを表示する)
	管理者 --> (環境情報を表示する)
	管理者 --> (データメンテナンス)
	(データメンテナンス) --> (バックアップを作成する)
	(データメンテナンス) --> (バックアップからリストアする)
	管理者 --> (ログメンテナンス)
	(ログメンテナンス) --> (ダウンロード)
	(ログメンテナンス) --> (削除)
}

@enduml
