@startuml
skinparam handwritten true
skinparam backgroundColor white
hide method

title ドメインモデル図：アクセス設定

package アクセスルール {
	class アクセスルールグループ {
		名称
		領域（プレフィックス）
		プラグイン
		ステータス（有効 / 無効）
	}
	class アクセスルール {
		NO
		設定順
		設定名
		アクセスルールグループID
		ユーザーグループID
		URL設定
		アクセス可否
		権限（全て / 表示・編集 / 表示のみ）
		ステータス（有効 / 無効）
	}
	note bottom
	・URL設定にはワイルドカードが利用できる
	・設定順は自動採番する
	endnote
}

class ユーザー

class ユーザーグループ {
	領域（プレフィックス）
	アクセス設定（フルアクセス・限定アクセス）	

}
note bottom
・site_configs に保存
endnote
	
ユーザー "0..*" --- "1..*" ユーザーグループ 
ユーザーグループ "1" -- "0..*" アクセスルール
アクセスルールグループ "1" -- "0..*" アクセスルール

@enduml
