@startuml
skinparam handwritten true
skinparam backgroundColor white
hide method

title ドメインモデル図：ユーザー

package ユーザー {
	
	class ユーザー {
		ログインアカウント名
		パスワード
		ニックネーム
		姓
		名
		Eメール
		ステータス
	}
	note bottom
	・ログインアカウント名は、255文字以内とすし入力必須とする
	・ログインアカウント名は重複して登録できない
	・ログインアカウント名は、半角英数字と「._-:/()#,@[]+=&;{}!$*)」で入力する
	・姓は50文字以内とし入力必須とする
	・名は50文字以内とする
	・ニックネームは255文字以内とする
	・ユーザーグループは必須とし自身のユーザーグループは変更できない
	・パスワードは6文字以上、255文字以内とする
	・パスワードは、半角英数字と「._-:/()#,@[]+=&;{}!$*)」で入力する
	・Eメールは255文字以内とし入力必須とする
	・Eメールは重複して登録できない
	・ステータスはシステム管理ユーザーしか変更できない
	・システム管理ユーザーのステータスは誰も変更できない
	・ログインアカウント名とEメールのどちらかとパスワードでログインできる
	・ステータスが有効でなければログインできない
	・ニックネームが登録されている場合、管理画面においてのユーザー名の表示はニックネームを利用する
	endnote

}

class ユーザーグループ

class パスワードリクエスト {
	ユーザーID
	リクエストキー
	使用済
}
note left
パスワードを再発行した場合対象レコードは
使用済となり利用できなくなる
endnote

class ログインストア {
	ユーザーID
	プレフィックス
	ストアキー
}
note left
ログイン対象（プレフィックス）ごとに
ストアキーを発行する
endnote

ユーザー "0..*" -left-> "0..*" ユーザーグループ
ユーザー "1" -up-> "0..*" パスワードリクエスト
ユーザー "1" -up-> "0..*" ログインストア

@enduml
