@startuml
skinparam handwritten true
left to right direction

hide circle
hide method


package DomainModel {
    class 商品 #F5A9BC
    class 予約商品 #F5A9BC
    class 在庫商品 #F5A9BC
    class カテゴリ
    class レビュー
    class カート
    class 注文 #CEF6F5
    class ウィッシュリスト
    class 登録情報 #A9C6F6
    mix_actor ユーザ

    商品 : 型番
    商品 : 価格
    登録情報 : メールアドレス

    ユーザ -> 登録情報 : has-one
    ユーザ --> カート
    カート o--> 商品 : has-many
    商品 <--o カテゴリ
    ユーザ o--> 注文
    注文 o--> 商品
    ユーザ --> ウィッシュリスト
    ウィッシュリスト o--> 商品
    ユーザ o--> レビュー
    レビュー <--o 商品

    商品 <|-- 予約商品 : is-a-kind-of
    商品 <|-- 在庫商品 : is-a-kind-of
}
@enduml
