@startuml
skinparam handwritten true
hide method

title ドメインモデル図：ユーザーグループ

package ユーザーグループ {
	
	class ユーザーグループ {
		ユーザーグループ名
		表示名
		認証プレフィックス
		お気に入り初期データ ※ baserCMS５で廃止
		コンテンツのドラッグ＆ドロップ移動機能を利用する
	}
	note bottom
	・ユーザーグループ名は、50文字以内とし入力必須とする
	・ユーザーグループ名は、半角のみ利用可能とする
	・ユーザーグループ名は重複して登録できない
	・表示名は、50文字以内とし入力必須とする
	・認証プレフィックスは入力必須とする
	endnote

}

class ユーザー

class アクセス制限設定

ユーザーグループ "1" -left-> "0..*" アクセス制限設定
ユーザーグループ "0..*" -right-> "0..*" ユーザー

@enduml
