@startuml

skinparam handwritten true
skinparam backgroundColor white

title ユースケース：カスタムコンテンツ

actor ユーザー
actor 運営者

package カスタムコンテンツ {
	left to right direction
	運営者 --> (新規追加する)
	運営者 --> (編集する)
	運営者 --> (削除する)
    運営者 --> (コピー)
    運営者 --> (プレビュー)
	(編集する) --> (フロントの記事一覧の表示件数)
	(編集する) --> (フロントの記事一覧の表示順)
	(編集する) --> (フロントに表示するウィジェットエリア)
	(編集する) --> (フロントで利用するレイアウトテンプレート)
	(編集する) --> (フロントで利用するレイアウトテンプレートの編集画面に遷移する)
	(編集する) --> (フロントで利用するコンテンツテンプレート)
	(編集する) --> (フロントで利用するコンテンツテンプレートの編集画面に遷移する)
    ユーザー --> (一覧表示)
    ユーザー --> (検索)
}

@enduml
