@startuml

skinparam handwritten true
skinparam backgroundColor white

title ユースケース：カスタムポスト

actor ユーザー
actor 閲覧ユーザー

package カスタムポスト {
	left to right direction
	ユーザー -up-> (カスタムポスト管理)
	(カスタムポスト管理) -up-> (カスタムポスト一覧を表示する)
	(カスタムポスト管理) -up-> (カスタムポストを作成する)
	(カスタムポスト管理) -up-> (カスタムポストを編集する)
	(カスタムポスト管理) -up-> (カスタムポストを削除する)
	(カスタムポスト管理) -up-> (カスタムポストを一括削除する)
	(カスタムポスト一覧を表示する) -up-> (記事を公開状態・非公開状態に設定する)
	(カスタムポスト一覧を表示する) -up-> (記事をコピーする)
	(カスタムポスト一覧を表示する) -up-> (記事を削除する)
	閲覧ユーザー -down-> (フロントのカスタムポスト一覧を表示する)
	閲覧ユーザー -down-> (フロントのカスタムポスト詳細を表示する)
}

@enduml
	
	
	
	
