@startuml

skinparam handwritten true
skinparam backgroundColor white

title ユースケース：カスタムフィールド

actor 運営者

package カスタムフィールド {
	left to right direction
	運営者 -down-> (一覧)
	(一覧) -down-> (有効化)
	(一覧) -down-> (無効化)
	(一覧) -down-> (コピー)
	(一覧) -down-> (削除)
	(一覧) -down-> (並べ替え)
	(一覧) -down-> (一括削除)
	(一覧) -down-> (一括有効化)
	(一覧) -down-> (一括無効化)
	運営者 -down-> (編集)
	運営者 -down-> (新規追加)
	(編集) -down-> (削除)
}

@enduml
