@startuml
skinparam handwritten true
skinparam backgroundColor white
hide circle
skinparam classAttributeIconSize 0

title ユーザー管理API

class Api\UsersController {
  + AuthenticationComponent
  + ログイン：login()
  + リフレッシュトークン取得：refresh_token()
  + ユーザー情報一覧取得：index()
  + 単一ユーザー情報取得：view()
  + ユーザー情報登録：add()
  + ユーザー情報編集：edit()
  + ユーザー情報削除：delete()
}

Api\UsersController -down[#Black]-> UsersService
Api\UsersController -up[#Black]-|> BcApiController

note "以下ユーザー管理と同じ" as note
UsersService .. note

@enduml
