@startuml
skinparam handwritten true
skinparam backgroundColor white
hide circle
skinparam classAttributeIconSize 0

title インストーラー

class InstallationsController {
  + 初期画面表示：index()
  + ステップ２：step2()
  + ステップ３：step3()
  + ステップ４：step4()
  + 完了画面表示：completed()
}

class InstallationsService {
}

class InstallationsServiceInterface {
  + 環境をチェックする：checkEnv()
  + データベース設定ファイルを作成する：createDatabaseConfig()
  + データベースの接続確認：checkDbConnection()
  + テーブル作成：constructionTable()
  + 初期データ読み込み：loadDefaultDataPattern()
  + システムデータ初期化：initSystemData()
  + SecuritySalt設定：setSecuritySalt()
  + 初期ユーザーを作成する：addDefaultUser()
  + コアプラグインをインストール：installCorePlugin()
  + プラグインのアセットへのシンボリックリンクを作成：createPluginSymLinks()
  + アップロード用初期フォルダを作成する：createDefaultFiles()
}

class UsersTable
class SiteConfigsTable
class PluginsTable

class User 
class SiteConfig
class Plugin

InstallationsController -down[#Black]-> InstallationsService
InstallationsService -left[dotted,#Black]-|> InstallationsServiceInterface
InstallationsService -down[#Black]-> UsersTable
InstallationsService -down[#Black]-> SiteConfigsTable
InstallationsService -down[#Black]-> PluginsTable
UsersTable -down[#Black]-> User
SiteConfigsTable -down[#Black]-> SiteConfig
PluginsTable -down[#Black]-> Plugin


@enduml
