@startuml
skinparam handwritten true
skinparam backgroundColor white
hide circle
skinparam classAttributeIconSize 0

title アクセス設定管理

class Admin\PermissionSettingsController {
  + アクセス設定一覧を表示：index()
  + アクセス設定編集：edit()
}

class PermissionSettingsService {
  + SiteConfigsTable
}

class PermissionSettingsServiceInterface {
  + アクセスグループ一覧を取得する：getIndex()
  + アクセスグループのリストを取得する：getList()
  + アクセスグループを更新：update()
}

class SiteConfigsTable {
}

class SiteConfig {
   + 設定名：name
   + 値：value
}

Admin\PermissionSettingsController -down[#Black]-> PermissionSettingsService
PermissionSettingsService -down[#Black]-> SiteConfigsTable
PermissionSettingsService -left[dotted,#Black]-|> PermissionSettingsServiceInterface
SiteConfigsTable -down[#Black]-> SiteConfig

@enduml
