@startuml
skinparam handwritten true
skinparam backgroundColor white
hide method

title ドメインモデル図：ブログコンテンツ

package ブログコンテンツ {
	
	class ブログコンテンツ {
		説明文
		フロントの記事一覧の表示件数
		フロントの記事一覧の表示順
		RSSフィードの出力記事件数
		コメント受付機能の利用状態
		コメント承認機能の利用状態
		コメントイメージ認証の利用状態
		タグ機能の利用状態
		フロントに表示するウィジェットエリア
		フロントで利用するコンテンツテンプレート  
		アイキャッチのリサイズサイズ
		記事概要の利用状態
	}
	
	class コンテンツ {
		タイトル
		URL
		公開状態
	}

}

ブログコンテンツ "1" - "1" コンテンツ 
ブログコンテンツ "1" -down- "0..*" ブログカテゴリ
ブログコンテンツ "1" -down- "0..*" ブログ記事

@enduml
