@startuml

skinparam handwritten true
skinparam backgroundColor white

title ユースケース：テーマファイル管理

actor 管理者

package テーマファイル管理 {
	left to right direction
	管理者 -down-> (現在のテーマ)
	(現在のテーマ) -down-> (一覧)
	(一覧) -down-> (削除)
	(一覧) -down-> (コピー)
	(一覧) -down-> (一括削除)
	(一覧) -down-> (タイプを変更する)
	(一覧) -down-> (フォルダを変更する)
	(現在のテーマ) -down-> (フォルダ新規作成)
	(現在のテーマ) -down-> (ファイル新規作成)
	(現在のテーマ) -down-> (ファイルをアップロードする)
	(現在のテーマ) -down-> (編集)
	管理者 -down-> (コアテンプレート)
	(コアテンプレート) -down-> (コアテンプレート一覧)
	(コアテンプレート一覧) -down-> (コアテンプレートのタイプを変更する)
	(コアテンプレート一覧) -down-> (コアテンプレートのフォルダを変更する)
	(コアテンプレート) -down-> (コアテンプレート確認)
	(コアテンプレート確認) -down-> (現在のテーマにコピー) 
}


@enduml
