@startuml
skinparam handwritten true
hide circle
skinparam classAttributeIconSize 0

title ユーザーAPI

class Admin\UsersController {
  + AuthenticationComponent
  ログイン()
  リフレッシュトークン取得()
  ユーザー情報一覧取得()
  単一ユーザー情報取得()
  ユーザー情報登録()
  ユーザー情報編集()
  ユーザー情報削除()
}

class UserService {
  + UsersTable
}

class UserServiceInterface {
  作成()
  編集()
  単一データ取得()
  一覧データ取得()
  初期データ取得()
  トークンを取得する()
}

class UsersTable {
  ユーザーに関連するよく使う項目を削除する()
  利用可能なユーザーを取得する()
  ユーザーが許可されている認証プレフィックスを取得する()
}

class User {
   + アカウント名
   + パスワード
   + 性
   + 名
   + メールアドレス
   + ニックネーム
   + 登録日
   + 編集日
   管理ユーザーかどうか判定する()
   整形されたユーザー名を取得する()
}

Admin\UsersController -down[#Black]-> UserService
Admin\UsersController -up[#Black]-|> BcApiController
UserService -left[dotted,#Black]-|> UserServiceInterface
UserService -down[#Black]-> UsersTable
UsersTable -down[#Black]-> User

@enduml
