@startuml
skinparam handwritten true
hide circle
skinparam classAttributeIconSize 0

title ユーザーAPI

class Api\UsersController {
  + AuthenticationComponent
  + ログイン：login()
  + リフレッシュトークン取得：refresh_token()
  + ユーザー情報一覧取得：index()
  + 単一ユーザー情報取得：view()
  + ユーザー情報登録：add()
  + ユーザー情報編集：edit()
  + ユーザー情報削除：delete()
}

class UserService {
  + UsersTable
}

class UserServiceInterface {
  + 作成：create()
  + 編集：update()
  + 単一データ取得：get()
  + 一覧データ取得：getIndex()
  + 初期データ取得：getNew()
}

class UsersTable {
}

class User {
   + アカウント名：name
   + パスワード：password
   + 性：real_name_1
   + 名：real_name_2
   + メールアドレス：email
   + ニックネーム：nickname
   + 登録日：created
   + 編集日：modified
}

Api\UsersController -down[#Black]-> UserService
Adpi\UsersController -up[#Black]-|> BcApiController
UserService -left[dotted,#Black]-|> UserServiceInterface
UserService -down[#Black]-> UsersTable
UsersTable -down[#Black]-> User

@enduml
