@startuml
skinparam handwritten true
hide circle
skinparam classAttributeIconSize 0

title API基本クラス構成

class Server {
  + run()
}

class Runner {
  + run()
}

class Application {
  + handle()
}

class ControllerFactory {
  + invoke()
}

class Admin\XxxsController {
  + 一覧データ取得：()
  + 単一データ取得()
  + 新規追加()
  + 編集()
  + 削除()
}

class BcApiController {
  + AuthenticationComponent
  + invokeAction()
  + render()
}

class JsonView {
  + render()
}

class XxxService {
  + XxxTable
}

class XxxServiceInterface {
  + 作成：create()
  + 編集：update()
  + 単一データ取得：get()
  + 一覧データ取得：getIndex()
  + 初期データ取得：getNew()
}

class XxxTable {
}

class Xxx {
}

note left
エンティティ
endnote

Server -right[#Black]-> Runner

Runner -right[#Black]-> Application

Application -right[#Black]-> ControllerFactory

ControllerFactory -right[#Black]-> Admin\XxxsController

Admin\XxxsController -right[#Black]-> JsonView
Admin\XxxsController -down[#Black]-> XxxService
Admin\XxxsController -up[#Black]-|> BcApiController

XxxService -left[dotted,#Black]-|> XxxServiceInterface
XxxService -down[#Black]-> XxxTable

XxxTable -down[#Black]-> Xxx

@enduml
