@startuml
skinparam handwritten true
hide circle
skinparam classAttributeIconSize 0

title コンテンツフォルダ管理

class BcContentsComponent {
    + setupAdmin()
    + setupFront()
    + settingForm()
    + getParentLayoutTemplate()
    + getTypes()
    + getContent()
    + getCrumbs()
    + beforeRender()
}

class Admin\ContentFoldersController {
    + AuthenticationComponent
    + BcMessageComponent
    + BcContentsComponent
    + edit()
    + delete()
    ※ add() は、APIを利用する
}

class BcAdminContentFolderHelper {
    + getFolderTemplateList()
    + getPageTemplateList()
    + getPublishLink()
}

class ContentFolderService {
    + ContentFoldersTable
}

class ContentFolderServiceInterface {
    + isOverPostSize()
    + getFolderTemplateList()
    + getPageTemplateList()
    + getPublishLink()
}

class ContentFoldersTable {
    + getParentTemplate()
    + getFolderTemplateList()
    + saveSiteRoot()
    + movePageTemplates()
    + setBeforeRecord()
}

class SearchIndiceTable {
    + reconstruct()
}

class ContentFolder {
    + id
    + folder_template
    + page_template
    + created
    + modified
}

class BcContentsBehavior {
    + initialize()
    + beforeMarshal()
    + afterSave()
    + beforeDelete()
    + afterDelete()
    + findPublished()
}

class ContentsTable {
    + updatingRelated
    + updateChildrenUrl()
    + getPath()
    + createContent()
    + softDelete()
    + removeFromTree()
}

class Content {
	entity_id
}

Admin\ContentFoldersController -left[#Black]-> BcContentsComponent
Admin\ContentFoldersController -down[#Black]-> ContentFolderService

BcAdminContentFolderHelper -left[#Black]-> ContentFolderService

ContentFolderService -left[dotted,#Black]-|> ContentFolderServiceInterface
ContentFolderService -down[#Black]-> ContentFoldersTable

ContentFoldersTable -right[#Black]-> SearchIndiceTable
ContentFoldersTable -left[#Black]-> BcContentsBehavior
ContentFoldersTable -left[#Black]-> ContentsTable
ContentFoldersTable -down[#Black]-> ContentFolder

BcContentsBehavior -left[#Black]-> ContentsTable

ContentsTable -left[#Black]-> Content

ContentFolder <-[#Black]- Content

@enduml
