@startuml
skinparam handwritten true
hide circle
skinparam classAttributeIconSize 0

title パスワード再発行

class Admin\PasswordRequestsController {
  + パスワード変更申請：entry()
  + パスワード変更：apply()
  + パスワード変更完了：done()
}

class PasswordRequestsTable {
  + 有効なパスワード変更情報を取得する：getEnableRequestData()
  + パスワードを変更する：updatePassword()
}

class PasswordRequest {
	+ ユーザーID：user_id
	+ リクエストキー：request_key
	+ 使用済：used
}

Admin\PasswordRequestsController -down[#Black]-> PasswordRequestsTable
PasswordRequestsTable -down[#Black]-> PasswordRequest

@enduml
