@startuml
skinparam handwritten true
skinparam backgroundColor white

title コンテンツフォルダ作成

participant "ContentFolderService" as Service
participant "ContentFolder" as Folder
participant "BcContentsBehavior" as Behavior
participant "Content" as Content

activate Service
activate Folder
activate Behavior
activate Content

Folder -> Behavior : initialize
note over Behavior
hasOneでコンテンツをフォルダに繋ぎこむ
endnote

note over Service
createメソッドの実行
endnote

Service -> Folder : patchEntity


Content -> Content: コンテンツ側beforeMarshal
note over Content
コンテンツテーブル側で
コンテンツのセットアップ
endnote

Behavior -> Content : afterMarshal
note over Behavior
contentフィールドが含まれてない場合
エラーを設定する。
プラグインとコンテンツの種類を設定する
endnote


Content -> Content : afterMarshal
note over Content
FrozenTime形式のデータ操作
endnote

Service -> Content : save

Content -> Content : beforeSave
note over Content
beforeSaveParentIdの設定と
DBに登録されるデータのurlエンコード
endnote

Content -> Content : afterSave
note over Content
Content:updateSystemData
Content:updateChildren
Content:updateRelateSubSiteContent
の実行
endnote
@enduml