@startuml
skinparam backgroundColor white
skinparam handwritten true
title "ucmitz系BcContentsBehavior"

start
#yellow :contentFolder:patchEntity;
#lightGreen :Contents:beforeMarshal;
#Pink :BcContentsBehavior:afterMarshal;
#lightGreen :Contents:afterMarshal;
#yellow :contentFolder:save;
#lightGreen :Contents:beforeSave;
#lightGreen :Contents:afterSave;
stop
@enduml

