@startuml
skinparam handwritten true
skinparam backgroundColor white

title ユースケース：固定ページ

actor ユーザー
actor 閲覧ユーザー

package 固定ページ {
	left to right direction
	閲覧ユーザー -up-> (固定ページを表示する)
	ユーザー -down-> (固定ページのプレビューを表示する)
	ユーザー -down-> (固定ページを作成する)
	ユーザー -down-> (固定ページを編集する)
	ユーザー -down-> (下書きを保存する)
	ユーザー -down-> (固定ページテンプレートを切り替える)
	ユーザー -down-> (記事にコードを埋め込む)
	note right of 記事にコードを埋め込む
	システム管理者のみが可能 ※ baserCMS５で廃止
	endnote
	ユーザー -down-> (固定ページの実体を削除する)
	note right of 固定ページの実体を削除する
	ゴミ箱を空にした時点で実行
	endnote
	ユーザー -down-> (固定ページをコピーする)
}

note left of 固定ページを表示する
フォルダ階層に連動したURLを発行する

例）https//localhost/folder/folder/page
endnote

@enduml
