@startuml

skinparam handwritten true
skinparam backgroundColor white

title ユースケース：アクセス制限設定

actor 管理者
actor ユーザー

package アクセス制限 {
	left to right direction
	管理者 --> (設定の一覧を表示する)
	管理者 --> (設定を登録する)
	管理者 --> (設定を編集する)
	管理者 --> (一覧より設定を有効・無効化する)
	管理者 --> (一覧より設定を複製する)
	管理者 --> (一覧より設定を削除する)
	管理者 --> (一覧より設定を一括で有効化・無効化・削除する)
	管理者 --> (一覧より設定順を並べ替える)
	管理者 --> (各画面より対象画面に対しての設定を登録する)
	ユーザー --> (画面表示時、アクセス制限対象の\nリンクを非表示にする)
	ユーザー --> (アクセス制限対象のURLにアクセスした際、\nダッシュボードにリダイレクトする)
}

@enduml
