@startuml

skinparam handwritten true
skinparam backgroundColor white

title ユースケース：アクセス設定

actor 管理者
actor ユーザー

package アクセス制限 {
	left to right direction
	管理者 --> (対象グループの\n基本アクセス設定\nを表示)
	(対象グループの\n基本アクセス設定\nを表示) --> (基本アクセス設定を変更)
	(対象グループの\n基本アクセス設定\nを表示) --> (アクセスルール\nグループ一覧)
	(アクセスルール\nグループ一覧) --> (アクセスグループ登録)
	(アクセスルール\nグループ一覧) --> (アクセスグループ編集)
	(アクセスルール\nグループ一覧) --> (アクセス\nルール一覧)
	(アクセス\nルール一覧) --> (設定を登録する)
	(アクセス\nルール一覧) --> (設定を編集する)
	
	(アクセス\nルール一覧) --> (一覧より設定を有効・無効化する)
	(アクセス\nルール一覧) --> (一覧より設定を複製する)
	(アクセス\nルール一覧) --> (一覧より設定を削除する)
	(アクセス\nルール一覧) --> (一覧より設定を一括で\n有効化・無効化・削除する)
	(アクセス\nルール一覧) --> (一覧より設定順を並べ替える)
	管理者 --> (各画面より\n対象画面に対しての\n設定を登録する)
	ユーザー --> (画面表示時、\nアクセス設定対象の\nリンクを非表示にする)
	ユーザー --> (アクセス設定対象のURLに\nアクセスした際、\n指定されたリダイレクト先に\nリダイレクトする)
}

@enduml
