@startuml
skinparam handwritten true
skinparam backgroundColor white

title ユースケース：サイト管理

actor 管理者

package サイト管理 {
	left to right direction
	管理者 --> (サイトの一覧を表示する)
	管理者 --> (サイトの一覧で表示件数を変更する)
	管理者 --> (サイトの一覧で公開状態を切り替える)
	管理者 --> (サイトの一覧からフロントページへ移動する)
	管理者 --> (サイトを作成する)
	管理者 --> (サイトを編集する)
	管理者 --> (サイトを削除する)
	管理者 --> (メインサイトを切り替える)
	管理者 --> (エイリアス連携を設定する)
	管理者 --> (デバイスを設定する)
	管理者 --> (言語を設定する)
	管理者 --> (テーマを切り替える)
	管理者 --> (アクセス方法を設定する（同一URL、自動リダイレクト）)
	note right of (アクセス方法を設定する（同一URL、自動リダイレクト）)
	デバイス、言語を設定した時のみ利用可能
	endnote
	管理者 --> (リンク自動変換を設定する)
	note right of リンク自動変換を設定する
	デバイスを設定した時のみ利用可能
	endnote
	管理者 --> (サイトを公開する)
}

@enduml
