@startuml
skinparam handwritten true
skinparam backgroundColor white
hide circle
skinparam classAttributeIconSize 0

title メールフィールドAPI

class Api\MailMessagesController {
  + 一覧取得：index()
  + 単一データ取得：view()
  + 新規追加：add()
  + 編集：edit()
  + 削除：delete()
  + 一括処理：batch()
  + CSVダウンロード：download()
}

class MailMessagesServiceInterface {
  + 単一データ取得：get()
  + 一覧データ取得：getIndex()
  + 初期データ取得：getNew()
  + 作成：create()
  + 編集：update()
  + 削除：delete()
}

Api\MailMessagesController -down[#Black]-> MailMessagesService
Api\MailMessagesController -up[#Black]-|> BcApiController
MailMessagesService -left[dotted,#Black]-|> MailMessagesServiceInterface

note "以下メールフィールド管理と同じ" as note
MailMessagesService .. note

@enduml
