@startuml

skinparam handwritten true
skinparam backgroundColor white

title ユースケース：メールコンテンツ

actor 管理者
actor 閲覧ユーザー

package メールコンテンツ {
	left to right direction
	閲覧ユーザー -up-> (メールフォームを表示)
	管理者 -down-> (追加)
	管理者 -down-> (変更)
	(変更) -down-> (送信先メールアドレス)
	(変更) -down-> (送信先名)
	(変更) -down-> (自動返信メール件名[ユーザー宛])
	(変更) -down-> (自動送信メール件名[管理者宛])
	(変更) -down-> (リダイレクトURL)
	(変更) -down-> (フォーム受付期間)
	(変更) -down-> (データベース保存)
	(変更) -down-> (イメージ認証)
	(変更) -down-> (SSL通信)
	(変更) -down-> (BCC用送信先メールアドレス)
	(変更) -down-> (フロントで利用するウィジェットエリア)
	(変更) -down-> (フロントで利用するメールフォームテンプレート)
	(変更) -down-> (フロントで利用するメールフォームテンプレートの編集画面に遷移する)
	(変更) -down-> (送信メールテンプレート)
	(変更) -down-> (送信メールテンプレートの編集画面に遷移する)
	管理者 -down-> (削除)
	管理者 -down-> (コピー)
}

@enduml
