@startuml
skinparam handwritten true
skinparam backgroundColor white
hide method

title ドメインモデル図：ブログコンテンツ

package ブログコンテンツ {
	
	class ブログコンテンツ {
		メールフォーム概要
		送信先メールアドレス
		BCC用送信先メールアドレス
		送信先名
		自動返信メール件名[ユーザー宛]
		自動送信メール件名[管理者宛]
		メールフォームテンプレート名
		送信メールテンプレート名
		リダイレクトURL
		イメージ認証
		ウィジェットエリア
		SSL通信
		データベース保存
		フォーム受付開始日
		フォーム受付終了日
	}
	
	class コンテンツ {
		タイトル
		URL
		公開状態
	}

}

ブログコンテンツ "1" - "1" コンテンツ 
ブログコンテンツ "1" -down- "0..*" メールフィールド
ブログコンテンツ "1" -down- "0..*" メールメッセージ

@enduml
