@startuml
skinparam handwritten true
skinparam backgroundColor white
hide method

title ドメインモデル図：コンテンツフォルダ

package コンテンツフォルダ {
	
	class フォルダ {
		フォルダーテンプレート
		固定ページテンプレート
	}
	
	class コンテンツ

}

class 子コンテンツ

フォルダ *- コンテンツ 
コンテンツ "1" -- "0..*" 子コンテンツ

@enduml
