@startuml
skinparam handwritten true
skinparam backgroundColor white
hide method

title ドメインモデル図：サイト

package サイト {
	
	class フォルダ
	
	class サイト {
		識別名称
		サイトエイリアス
		サイト名
		サイトタイトル
		サイト基本キーワード
		サイト基本説明文
		メインサイトID
		エイリアスを利用してメインサイトと自動連携する
		デバイス設定
		言語設定
		メインサイトと同一URLでアクセス
		メインサイトから自動的にリダイレクト
		全てのリンクをサブサイト用に変換する
		テーマ
		公開状態
	}
	note bottom
	・サイトを作成するとそのサイトのルートフォルダを作成する。
	・サイトを非公開にするとフォルダの公開状態も非公開となる。
	・サイトを削除するとそのサイトのルートフォルダ以外を論理削除し、ルートフォルダは物理削除する。
	endnote

}

class メインサイト

フォルダ -* サイト 
サイト "0..*" -> "1" メインサイト

@enduml
