@startuml
skinparam handwritten true
skinparam backgroundColor white
hide method

title ドメインモデル図：ユーザーグループ

package ユーザーグループ {
	
	class ユーザーグループ {
		ユーザーグループ名
		表示名
		認証プレフィックス
		コンテンツのドラッグ＆ドロップ移動機能を利用する
	}
	note bottom
	・ユーザーグループ名は、50文字以内とし入力必須とする
	・ユーザーグループ名は、半角のみ利用可能とする
	・ユーザーグループ名は重複して登録できない
	・表示名は、50文字以内とし入力必須とする
	・認証プレフィックスは、複数の認証領域を設定している場合にのみ入力欄を表示
	・認証プレフィックスは表示されている場合に入力必須とする
	・admins グループの認証プレフィックスにおいて「管理システム」は削除できない
	・admins グループは、ユーザーグループ名の変更、削除、および、アクセス制限の設定はできない。
	endnote

}

class ユーザー

class アクセス制限設定

ユーザーグループ "1" -left-> "0..*" アクセス制限設定
ユーザーグループ "0..*" -right-> "0..*" ユーザー

@enduml
