@startuml

skinparam handwritten true
skinparam backgroundColor white

title ユースケース：ブログコンテンツ

actor 管理者
actor 閲覧ユーザー

package ブログコンテンツ {
	left to right direction
	閲覧ユーザー -up-> (フロントの記事一覧を表示)
	管理者 -down-> (追加)
	管理者 -down-> (変更)
	(変更) -down-> (フロントの記事一覧の表示件数)
	(変更) -down-> (フロントの記事一覧の表示順)
	(変更) -down-> (RSSフィードの出力記事件数)
	(変更) -down-> (コメント受付機能の利用状態)
	(変更) -down-> (コメント承認機能の利用状態)
	(変更) -down-> (コメントイメージ認証の利用状態)
	(変更) -down-> (タグ機能の利用状態を変更する)
	(変更) -down-> (フロントに表示するウィジェットエリア)
	(変更) -down-> (フロントで利用するレイアウトテンプレート)
	(変更) -down-> (フロントで利用するレイアウトテンプレートの編集画面に遷移する)
	(変更) -down-> (フロントで利用するコンテンツテンプレート)
	(変更) -down-> (フロントで利用するコンテンツテンプレートの編集画面に遷移する)
	(変更) -down-> (アイキャッチのリサイズサイズを変更する)
	(変更) -down-> (記事概要の利用状態を変更する)
	管理者 -down-> (削除)
	管理者 -down-> (コピー)
}

@enduml
