@startuml
skinparam handwritten true
skinparam backgroundColor white
hide circle
skinparam classAttributeIconSize 0

title カスタムエントリー管理

class Admin\CustomEntriesController {
  + 一覧を表示：index()
  + 新規追加：add()
  + 編集：edit()
  + 削除：delete()
	+ 複製：copy()
	+ 公開状態に設定：publish()
	+ 非公開状態に設定：unpublish()
}

class CustomEntriesService {
  + CustomEntriesTable
}

class CustomEntriesServiceInterface {
  + 初期データ取得：getNew()
  + 作成：create()
  + 編集：update()
  + 削除：delete()
  + 単一データ取得：get()
  + 一覧データ取得：getIndex()
	+ コピー：copy()
	+ 公開状態かどうか確認：allowPublish()
	+ 一括処理：batch()
	+ 公開状態に設定：publish()
	+ 非公開状態に設定：unpublish()
	+ 複数のIDよりタイトルのリストを取得：getTitlesById()
	+ コントロールソース取得：getControlSource()
	+ ファイルアップロード設定：setupUpload()
}

class CustomEntriesTable {
}

class CustomEntry {
		+ カスタムテーブルID：custom_content_id
		+ NO：no
		+ スラッグ：name
		+ タイトル：title
		+ 作成者ID：author_id
		+ 公開状態：publish
		+ 投稿日：posted
		+ 公開開始日：publish_begin
		+ 公開終了日：publish_end
		+ サイト内検索より除外：exclude_search
		+ アイキャッチ：eye_catch
}

Admin\CustomEntriesController -down[#Black]-> CustomEntriesService
CustomEntriesService -down[#Black]-> CustomEntriesTable
CustomEntriesService -left[dotted,#Black]-|> CustomEntriesServiceInterface
CustomEntriesTable -down[#Black]-> CustomEntry


@enduml
