@startuml
skinparam handwritten true
skinparam backgroundColor white
hide circle
skinparam classAttributeIconSize 0

title カスタムフィールド管理

class Admin\CustomFieldsController {
  + 一覧取得：index()
  + 新規追加：add()
  + 編集：edit()
  + 削除：delete()
  + コピー：copy()
  + 有効化：publish()
  + 無効化：unpublish()
  + 並び順更新：update_sort()
}

class CustomFieldsService {
  + CustomFieldsTable
}

class CustomFieldsServiceInterface {
  + 単一データ取得：get()
  + 一覧データ取得：getIndex()
  + リスト取得：getList()
  + 初期データ取得：getNew()
  + 作成：create()
  + 編集：update()
  + 削除：delete()
  + コピー：copy()
  + 有効状態にする：publish()
  + 無効状態にする：unpublish()
  + 並び順を変更する：changeSort()
}

class CustomFieldsTable {
}

class CustomField {
	+ カスタムテーブルID：custom_table_id
	+ カスタムフィールドNO：no
	+ 親ID：parent_id
	+ ツリー構造左位置：lft
	+ ツリー構造右位置：rght
	+ 項目見出し：head
	+ フィールド名：name
	+ フィールドタイプ：type
	+ ステータス：status
	+ 入力必須とする：required
	+ 前見出し：before_head
	+ 後見出し：after_head
	+ 説明文：description
	+ 注意書き：attention
	+ 登録日：created
	+ 変更日：modified
	+ グループ入力チェック：group_valid
	+ オプション：options
	+ クラス：class
	+ 初期値：default_value
	+ 入力チェック：validate
	+ 正規表現入力：regex
	+ エラー用文言：regex_error_message
	+ 文字数カウンターを表示する：counter
	+ 自動変換：auto_convert
	+ プレースホルダー：placeholder
	+ サイズ：size
	+ テキスト行数：rows
	+ 最大値：max_length
	+ 選択肢：source
	+ メタ情報：option_meta
}

Admin\CustomFieldsController -down[#Black]-> CustomFieldsService
CustomFieldsService -down[#Black]-> CustomFieldsTable
CustomFieldsService -left[dotted,#Black]-|> CustomFieldsServiceInterface
CustomFieldsTable -down[#Black]-> CustomField

@enduml
