@startuml
skinparam handwritten true
skinparam backgroundColor white
hide circle
skinparam classAttributeIconSize 0

title ブログカテゴリAPI

class Api\BlogCategoriesController {
  + サイト一覧取得：index()
  + 単一サイト取得：view()
  + リスト取得：list()
  + サイト新規追加：add()
  + サイト編集：edit()
  + サイト削除：delete()
  + 一括処理：batch()
}

Api\BlogCategoriesController -down[#Black]-> BlogCategoriesService
Api\BlogCategoriesController -up[#Black]-|> BcApiController

note "以下ブログカテゴリ管理と同じ" as note
BlogCategoriesService .. note

@enduml
